# =========================================================
# HIVECARE BACKEND
# =========================================================

spring.application.name=hivecare-backend


# =========================================================
# SERVER
# =========================================================

# Render automatically provides PORT.
# Locally it will use 8080.

server.port=${PORT:8080}


# =========================================================
# MYSQL / AIVEN
# =========================================================

spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver


# =========================================================
# JPA / HIBERNATE
# =========================================================

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=false

spring.jpa.open-in-view=false


# =========================================================
# FRONTEND
# =========================================================



app.frontend.url=${FRONTEND_URL:https://hivecare.vercel.app}


# =========================================================
# RAZORPAY
# =========================================================

razorpay.key.id=${RAZORPAY_KEY_ID}
razorpay.key.secret=${RAZORPAY_KEY_SECRET}


# =========================================================
# GROQ AI
# =========================================================

groq.api.key=${GROQ_API_KEY}


# =========================================================
# BREVO EMAIL
# =========================================================

brevo.api.key=${BREVO_API_KEY}

brevo.sender.email=${BREVO_SENDER_EMAIL}

brevo.sender.name=${BREVO_SENDER_NAME}


# =========================================================
# GOOGLE OAUTH
# =========================================================

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}

spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}

spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

# ==========================================
# JWT SECURITY
# ==========================================

app.jwt.secret=${JWT_SECRET}

app.jwt.expiration=${JWT_EXPIRATION}

